settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: app-getrewell-com # unique identifier
    name: app.getrewell.com
    description: 'Rewell App Prod' # default=empty
    url: 'https://app.getrewell.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: api2-getrewell-com
    name: api2.getrewell.com
    description: 'Rewell Backend Prod'
    url: 'https://api2.getrewell.com/'

  - id: sapp-getrewell-com
    name: sapp.getrewell.com
    description: 'Rewell App Staging'
    url: 'https://sapp.getrewell.com/'

  - id: sapi2-getrewell-com
    name: sapi2.getrewell.com
    description: 'Rewell Backend Staging'
    url: 'https://sapi2.getrewell.com/'

  - id: tapp-getrewell-com
    name: tapp.getrewell.com
    description: 'Rewell App Test'
    url: 'https://tapp.getrewell.com/'
    
  - id: tapi2-getrewell-com
    name: tapi2.getrewell.com
    description: 'Rewell Backend Test'
    url: 'https://tapi2.getrewell.com/'

  - id: api-xtrack-labtory-com-ar
    name: api-xtrack.labtory.com.ar
    description: 'Xtrack Backend'
    url: 'https://api-xtrack.labtory.com.ar'

  - id: test-api-xtrack-labtory-com-ar
    name: test-api-xtrack.labtory.com.ar
    description: 'Xtrack Backend Test'
    url: 'https://test-api-xtrack.labtory.com.ar'
